### ISSUE TITLE
фид не создаётся

### ISSUE THREAD

**Issue by Konstantinych** [Teplitsa/tst-yandex-feed#10]
Здравствуйте!!!
Решил воспользоваться возможностями Вашего плагина Яндекс.Новости.
Столкнулся с непонятной мне трудностью. Не могу отобразить в броузере соответствующую трансляцию http://funtattoo.ru/yandexnews/. Она просто не существует. Как Вы советуете в одной из статей, в администраторской я захожу в Настройки, затем в Постоянные ссылки, но это не помогает. Скрин настроек плагина https://yadi.sk/i/VrOMhoDAhtMDE. Буду признателен за помощь.
Спасибо.

**Comment by foralien** [comment]
День добрый!
Спасибо за скрин с настройками... думаю, тут может быть 2 проблемы сразу
1 - не сбросились правила роутинга, поэтому страница. По идее заход на постоянные ссыли должен был это исправить, но тем не менее...
2 - в вас в типах записей для отображения пусто - вероятно наш плагин некорректно обрабатывает эту ситуацию: мы проверим и исправим это, однако вам лучше там что-нибудь указать: post например - если у вас основные записи типа post или есть зарегистрированы другие кастомные типы записей, тогда их через запятую
И после этого снова зайти на постоянные ссылки.

**Comment by foralien** [comment]
и еще насколько я вижу у вас не активны "красивые" пермалинки на сайте - в этом случае история с кастомной странице не работает совсем

**Comment by Konstantinych** [comment]
1) Поставил в "Типы записей: post". Результат такой же - фид не существует.
2) Т.е. если у меня "Постоянные ссылки: По умолчанию" в виде "http://funtattoo.ru/?p=17034" настроить свой адрес для фида я не могу вообще? Правильно понимаю?
3) Как я понял вот этот адрес "http://funtattoo.ru/?yandex_feed=news"  - это умолчальный фид, который я могу спокойно экспортировать в Яндекс?
4) Что такое "Связанные ссылки" в настройках для каждого поста и как ими пользоваться?
Спасибо.

**Comment by foralien** [comment]
1-3) точно так... если у вас ссылки вида http://funtattoo.ru/?p=17034, но настроить кастомную страницу средствами плагина без дополнительного кода не получится (с дополнительным - не знаю если честно, это поле для эксперимента).
Однако фид по умолчанию по "дефолтному" урлу http://funtattoo.ru/?yandex_feed=news - доступен и будет работать.
4) Связанные ссылки - это доп. поле, в котором можно указывать ссылки на внешние ресурсы, на которые вы ссылаетесь и которые могут быть обозначены как релевантные. В трансляции для них в этом случае предусмотрены отдельные элементы, подробнее в описании формата http://partner.news.yandex.ru/gates/getDoc.xml?type=tech

**Comment by Konstantinych** [comment]
Ок! Спасибо большое! Читайте наш журнал - http://funtattoo.ru !!!

**Comment by Konstantinych** [comment]
И снова здравствуйте!!! Есть очередной вопрос по обсуждаемому плагину.
Всё работает, всё экспортируется, но вот когда ставишь галку "Исключить запись из трансляции Яндекс.Новости". Делаешь "Сохранить". Галка сбрасывается, а пост всё равно экспортируется.
А существует принципиальная необходимость, обусловленная правилами я.новостей исключать из экспорта некоторые публикации. Вот...

**Comment by DenisCherniatev** [comment]
Ошибку удалось повторить. Исправим в ближайшем обновлении.

**Comment by DenisCherniatev** [comment]
Эта ошибка возникает в случае, если в настройках поле "Типы записей для трансляции" пустое. Если его заполнить, указав значение post, то исключение записей из ленты должно заработать.

**Comment by DenisCherniatev** [comment]
Выпущена новая версия плагина. После обновления плагина на сайте проблема должна исчезнуть.
