### ISSUE TITLE
Исключить вводные данные из <yandex:full-text>

### ISSUE THREAD

**Issue by mediapotok** [Teplitsa/tst-yandex-feed#12]
Добрый день!
У большинства изданий в начале новости идут т.называемые вводные данные, типа "Москва - 15 июля, РИА Новости". Однако Яндекс просит исключать эту информацию из текста новости, т.е. выводить за рамки <yandex:full-text>. Подскажите, каким образом можно это сделать?

p.s. еще не работает галка исключения конкретной новости из фида. после сохранения она просто снимается и новость попадает в фид. сайт http://potokmedia.ru/

**Comment by foralien** [comment]
Какими-то средствами плагина это сделать вряд ли возможно, особенно если это просто вставленный текст. Если это какое-то кастомное поле - тогда можно написать функцию, которая бы отфильтровывала эти данные.

Про исключение из фида - известно, что галка не работате, когда в настройках плагина не указан ни один пост-тайп (тип контента), укажите там те типы, которые используются в трансляции - post например

**Comment by DenisCherniatev** [comment]
Плагин обновлен. Ошибку с галкой исключения из фида воспроизвести не удалось. Тестирование производилось на разных версиях WordPress в разных состояниях и с разными наборами плагинов. В связи с этим прошу обновить плагин до последней версии и попробовать воспроизвести ошибку. Если она не исчезнет, то, скорее всего, дело в конфликет плагина tst-yandex-feed с одним из ваших плагинов.

**Comment by corradych** [comment]
Весь текст сливается в один абзац. Каким образом можно оставить абзацы? Чтоб не фильтровался тег <p>

**Comment by DenisCherniatev** [comment]
На данный момент наш плагин удаляет HTML разметку из текста для тэгов description и yandex:full-text. Поэтому вывод обзацев невозможен.

Добавление HTML разметки в yandex:full-text невозможно по требованиям Яндекса. А вывод HTML разметки внутри тэга description мы рассмотрим в следующих версиях плагина. Спасибо за предложение!

**Comment by corradych** [comment]
Дело в том, что данный формат уже, так сказать, "пошел в народ" и используется не только для экспорта контента на Яндекс.Новости, но и для других агрегаторов, или просто для обмена контентом. И бывает, что хотя бы абзацы нужны. Вот например у меня сейчас такая необходимость возникла.
