### ISSUE TITLE
Предложение по улучшению согласно требованиям яндекса

### ISSUE THREAD

**Issue by majestica** [Teplitsa/tst-yandex-feed#13]
Доброго времени суток, установил ваш плагин на вордпресс, отправил в яндекс ссылочки на экспорт и вот, что они мне ответили 
"- Наличие элемента <media:thumbnail> в <media:group> при экспорте видео крайне желательно. Пример оформления этого элемента можно увидеть на странице https://partner.news.yandex.ru/tech.pdf."
Прошу учесть замечание яндекса и добавить данный функционал. Спасибо
зЫ возможно этот функционал есть но я не нашел в faq его описания(

**Comment by foralien** [comment]
Пока не вижу возможности как это сделать.
Мы поддерживаем видео только через ссылки с YouTube - при этом информации о thumbnail, как отдельном файлей у нас нет никакой, а делать дополнительный запрос по API для этого как-то не рационально.

**Comment by majestica** [comment]
судя по коду в  yandexnews-feed-by-teplitsa/inc/feed.php
<media:group>
<media:player url="<?php echo esc_url($media_obj['url']);?>" />
<?php if(!empty($media_obj['thumb'])) { ?>
<media:thumbnail url="<?php echo esc_url($media_obj['thumb']);?>"/>
<?php }?>
</media:group>

оно должно приходить в $media_obj['thumb']) но оно не проходит проверку на иф и там пусто поэтотому информацию не выводит.

Так в yandexnews-feed-by-teplitsa/inc/tst-yandex-feed-core.php

в регекспе мы получим на выходе айди на видеозапись нам осталось ее подставить для получения того же thumbnail. Насколько я понимаю данный функционал планировался но не был доконца реализован?

//youtube
		$youtube_regexp = "/(?:http(?:s)?:\/\/)?(?:www\.)?(?:youtu\.be\/|youtube\.com\/(?:(?:watch)?\?(?:.*&)?v(?:i)?=|(?:embed|v|vi|user)\/))([\w-]{10,12})/";
		preg_match_all($youtube_regexp, $out, $matches);		
		if(isset($matches[0]) && !empty($matches[0]))
			$res = array_merge($res, $matches[0]); //append links
		
		//@to_do: add another video providers
		
		//modify $res to be able add thumbnails
		$return = array();
		if(!empty($res)){ foreach($res as $i => $url) {
			$return[] = array('url' => $url, 'thumb' => '');
		}}

зЫ а чем вам не нравиться дергать по апи и получить тумблу по урлу типа http://img.youtube.com/vi/<insert-youtube-video-id-here>/maxresdefault.jpg 

в цикле можно будет получать тумблу для всех видео в посте так как хочет яндекс.

**Comment by foralien** [comment]
ну ровно по этой причине и не был - что неоткуда взять инфу о thumbnail, кроме как обратившись к API ютуба... если видео много - то много общений  и все такое, нужно думать над отпимизацией... на тот момент решили, что это овер для нашего небольшого плагинчика... возможно, вернемся в этом вопросу позже...

**Comment by majestica** [comment]
хорошо, есть другой вариант берем thumbnail по апи с ютуба сохраняем локально в медиатеке WP и ставим ссылку на него в media:thumbnail в media:group (я именно так и решил этот вопрос потому что яндекс очень настаивал на индексации видеозаписей в фиде).... других вариантов нет и не будет.  Я Вас услышал спасибо.

**Comment by foralien** [comment]
да вариант с локальным сохранением выглядит разумным - спасибо за идею.
подумаем.

**Comment by DenisCherniatev** [comment]
Добавлен показ ссылки на тамбик для видео с youtube. Также оптимизирована XML структура media:group, в результате чего теперь в фиде показывается ссылка на само видео.

**Comment by majestica** [comment]
круто, спасибо=) оно будет отрабатывает ссылки на тамбик для видео с ютуба для всех видеозаписей в записи вордпресса? я имею ввиду если я добавлю 3 видео в новости оно их все отработает?

**Comment by DenisCherniatev** [comment]
Да, плагин должен обработать все ссылки на youtube и отразить это  в ленте.

**Comment by majestica** [comment]
Доброго времени суток, прошу обраратить внимание в этом документе  https://partner.news.yandex.ru/tech.pdf   на часть 

Внимание: 
ширина тумбнейла должна быть не меньше 240 пикселей, длина не меньше 300 пикселей. 
Видео, сопровождающееся тумбнейлом размером менее 300*240 пикселей, не будет проиндексировано.

в патче выложенном Вами видео привью размеров 120 x 90 в индекс оно не попадет...

**Comment by DenisCherniatev** [comment]
Спасибо за замечание. Код в репозитории исправлен. Вскоре выйдет обновление плагина.

**Comment by DenisCherniatev** [comment]
Плагин обновлен.

**Comment by majestica** [comment]
Круто, спасибо за фидбек.

**Comment by majestica** [comment]
Подскажите пожалуйста, делаю в партнерке яндекса проверку на валидацию фида оно выдает
"Не удалось определить mime-тип тэга <media:content>"   никак не могу понять в чем дело... может вы знаете?

**Comment by majestica** [comment]
Вот, что мне ответила поддержка Яндекса

"Если вы транслируете ссылки на ваше видео, которое размещено на YouTube, то элемент <media:content> стоит отставлять пустым. Достаточно указывать ссылку в <media:player>."
и это "При этом каждое видео необходимо размещать в отдельном <media:group>."

**Comment by DenisCherniatev** [comment]
Спасибо за информацию. Исследуем проблему и выпустим исправление в ближайшие дни.

**Comment by majestica** [comment]
Вообщем я решил проблему 
должно иметь такой вид

<media:group>
<media:player url="https://www.youtube.com/embed/1234"/>
<media:thumbnail url="https://img.youtube.com/vi/1234/0.jpg"/>
</media:group>
<media:group>
<media:player url="https://www.youtube.com/embed/12345"/>
<media:thumbnail url="https://img.youtube.com/vi/12345/0.jpg"/>
</media:group>
<media:group>
<media:player url="https://www.youtube.com/embed/123456"/>
<media:thumbnail url="https://img.youtube.com/vi/123456/0.jpg"/>
</media:group>


для этого в файле feed.php

<code><media:group>
<?php foreach($media as $media_obj):?>
<media:content url="<?php echo esc_url($media_obj['url']);?>">
<media:player url="<?php echo esc_url($media_obj['url']);?>" />
<?php if(!empty($media_obj['thumb'])) { ?>
<media:thumbnail url="<?php echo esc_url($media_obj['thumb']);?>"/>
<?php }?>
</media:content>
<?php endforeach; ?>
</media:group>
<?php endif;?></code>

заменяем на

<code><?php foreach($media as $media_obj):?>
<media:group>
<media:player url="<?php echo esc_url($media_obj['url']);?>" />
<?php if(!empty($media_obj['thumb'])) { ?>
<media:thumbnail url="<?php echo esc_url($media_obj['thumb']);?>"/>
<?php }?>
</media:group>
<?php endforeach; ?>
<?php endif;?></code>

**Comment by DenisCherniatev** [comment]
Спасибо! Ваши исправления включены репозиторий. У вас есть возможность провалидировать фид с несколькими видео с youtube, который генерирует последняя версия из репозитория? Если да, то провалидируйте пожалуйста и сообщите о результатах.

**Comment by majestica** [comment]
Я проверил, все ок как с одним видео так и с несколькими, фид корректен.

**Comment by DenisCherniatev** [comment]
Спасибо за помощь. Об обновлении плагина сообщим дополнительно.

**Comment by DenisCherniatev** [comment]
Плагин обновлен.
