### ISSUE TITLE
Миниатюры в постах

### ISSUE THREAD

**Issue by krogstall** [Teplitsa/tst-yandex-feed#14]
Подскажите пожалуйста, как можно исключить ссылки на миниатюры от поста из фида, но оставить прикрепленные медиафайлы?

**Comment by DenisCherniatev** [comment]
Пока такой возможности нет. Но вы можете исправить код в файле плагина, чтобы их исключить:
Исправить нужно файл inc/feed.php

Если удалите этот кусок, то исключите все миниатюры записи:
<?php //enclosures
	$enclosure = La_Yandex_Feed_Core::item_enclosure();
	if(!empty($enclosure)): foreach($enclosure as $i => $img):
?>
<enclosure url="<?php echo esc_url($img['url']);?>" type="<?php echo esc_attr($img['mime']);?>"/>
<?php endforeach; endif;?>

Если удалите этот кусок, то исключите тамбнейлы видео в списке медиафайлов:
<?php if(!empty($media_obj['thumb'])) { ?>
<media:thumbnail url="<?php echo esc_url($media_obj['thumb']);?>"/>
<?php }?>

Дайте знать, какой из вариантов вам подошел, и мы добавим нужную функцию в ближайшем обновлении.

**Comment by kryshtopa** [comment]
Благодарю вас за этот прекрасный плагин!
Есть предложение для следующей версии.
При прохождении проверки корректности экспортного фида, получил от Яндекса письмо:

"Здравствуйте!
В ваш экспортный файл необходимо внести еще некоторые коррективы:
В теге pdalink нужно указывать ссылку на адаптированную для мобильных устройств версию сообщения. В случае, если такой версии страниц на сайте нет, этот тег нужно исключить.
"

Я проблему решил простым удалением строки из feed.php. Но многим пользователям будет наверняка полезна возможность работы с этим параметром из админки.

**Comment by DenisCherniatev** [comment]
Спасибо за информацию. Рассмотрим включение данной опции в следующую версию.

**Comment by DenisCherniatev** [comment]
Выпущена новая версия плагина, в которой добавлена опция удаления тэга pdalink. Будем благодарны за тестирование и отзыв.
