### ISSUE TITLE
Произвольные авторы

### ISSUE THREAD

**Issue by KirillKrasyuk** [Teplitsa/tst-yandex-feed#15]
Иногда есть потребность привязать автора не того, который публиковал статью, а другой. Для вывода в шаблон используются кастомные поля в статьях и выводится таким типом в шаблоне:
<?=  get_post_meta($post->ID, 'author_name', true); ?>

Было бы не плохо добавить поле в админке: название кастомного поля автора.

У себя я это решил методом патча вашего плагина. 

p.s. если дойдут руки, сделаю сам и залью сюда.

**Comment by DenisCherniatev** [comment]
Пока вводить такую опцию не планируется. Спасибо за пример решения вашей проблемы, он может пригодиться другим пользователям плагина.
