### ISSUE TITLE
Количество постов

### ISSUE THREAD

**Issue by kpik** [Teplitsa/tst-yandex-feed#16]
Здравствуйте, подскажите пожалуйста как ограничить количество новостей в ленте? Глобальные настройки не действуют на плагин.

**Comment by DenisCherniatev** [comment]
Количество записей не ограничено. Ограничение есть только по дате публикации. Яндекс требует, чтобы в ленте показывались только записи за последнюю неделю.

**Comment by kpik** [comment]
Я бы хотел в плагине для wp ограничить количество отдаваемых новостей, например только последние 10

**Comment by DenisCherniatev** [comment]
К сожалению такой опции пока-что нет. Вы можете исправить код плагина.

В файле plugins/yandexnews-feed-by-teplitsa/inc/tst-yandex-feed-core.php нужно исправить строчку 
$query->query_vars['posts_per_page'] = -1;
на
$query->query_vars['posts_per_page'] = 10;

**Comment by kpik** [comment]
Благодарю за помощь.
