### ISSUE TITLE
Исключение отдельных записей не работает

### ISSUE THREAD

**Issue by vladimk** [Teplitsa/tst-yandex-feed#17]
Добрый день! 

Нужно исключать отдельные записи из трансляции Яндекс.Новостей (погода, неновостные статьи и т.п.).
Отмечаю чекбокс "Исключить, не смотря на глобальные настройки", однако после публикации или обновления поста, чекбокс оказывается снова снят и пост продолжает транслироваться в фид.

В глобальных настройках установлена фильтрация по ID для рубрики (выводятся записи только из одной определенной рубрики). Скрин настроек плагина http://joxi.ru/vDr8dEkcPo5Vr6

Сообщения о проблеме есть в комментариях к постам про плагин на сайте "Теплицы", однако решения там не нашел. 

--
P.S. Спасибо за плагин! И отдельное спасибо за последнее обновление, решившее проблемы с дублированием миниатюр при использовании лайтбокса для изображений.

**Comment by DenisCherniatev** [comment]
Чтобы решить проблему, нужно в настройках плагина заполнить поле "Типы записей для трансляции". В вашем случае туда надо вписать тип post
После этого исключите из трансляции ненужные записи заново и они должны будут исчезнуть из фида.

**Comment by vladimk** [comment]
Спасибо! Все заработало.
