### ISSUE TITLE
Произошла ошибка; возможно, лента недоступна. Повторите попытку позже.

### ISSUE THREAD

**Issue by AlexKoho** [Teplitsa/tst-yandex-feed#18]
Здравствуйте,
установил плагин, по урлу все отлично работает: http://googlephones.ru/yandex/news 
а виджет на самом сайте http://googlephones.ru/ выдает ошибку: Произошла ошибка; возможно, лента недоступна. Повторите попытку позже.
Хотя еще вчера-позавчера все работало, т.е. и на страницах сайта виджет RSS корректно отображал записи.
Этот же самый виджет, стандартную ленту читает: http://googlephones.ru/feed , а вашу не видит: http://googlephones.ru/yandex/news - "Nothing found for  Yandex News"
Что могло случится? Не принципиально, конечно = виджет то можно и убрать (главное по ссылке работает), но хотелось бы понять причину сего странного казуса!
Спасибо.
P.S. Еще вопрос: почему в ленте в теге <description> после описания попадается "%123%" после него идет заголовок из <title> и все это внутри тега <description> ? Это так у меня только? Посмотрел у других СМИ - не увидел такого. Или это так надо? Зачем?

**Comment by DenisCherniatev** [comment]
Если в ленте новости видны, а в виджете нет, то скорее всего проблема в виджете. Возможно он не поддерживает какие-то из тэгов, которые встречаются в ленте. В зависимости от контента новости эти тэги могут появляться и исчезать. Поэтому поведение виджета меняется.

Дополнительной строки "%123%" не обнаружено. Возможно какой-то плагин добавляет ее в описание при редактировании записи или при получении контента программно с целью дальнейшего преобразования на стороне клиента. Так как в ленте клиентский код не выполняется, то эта строка остается необработанной и показывается в исходном виде.
