### ISSUE TITLE
При попытке забрать ленту один из агрегаторов получае ошибку HTTP code: http://prntscr.com/9onutx

### ISSUE THREAD

**Issue by hulaladen** [Teplitsa/tst-yandex-feed#19]
При попытке забрать ленту один из агрегаторов (новотека) получае ошибку HTTP code: http://prntscr.com/9onutx 

Для того, чтобы решить проблему, нужно разрешить их роботу забирать RSS-ленту. Робот Новотеки использует User-Agent "libwww-perl.XXXX", где XXXX - это число, которое может меняться. (это ответ тех поддержки Новотеки)

Я понимаю, что программа сделана в первую очередь для яндекс новостей, но, возможно, у вас будет возможность добавить такую штуку, чтобы позволить Новотеке также брать оттуда новости?

**Comment by DenisCherniatev** [comment]
Плагин в первую очередь учитывает требования Яндекса к ленте новостей. Поэтому доработка плагина под другие агрегаторы имеет низкий приоритет и оптимизация под новотеку в ближайшем будущем не планируется. Но мы будем иметь ввиду описанную проблему.

**Comment by GSuvorov** [comment]
Проблема связана с настройками CF,  плагин ни при чем.

**Comment by hulaladen** [comment]
Спасибо большое за пояснение. Поскажите, вомзожно, вы можете подсказать что следует поменять в настройках CF, чтобы плагин работал корректно?
