### ISSUE TITLE
Убрать тизер

### ISSUE THREAD

**Issue by Komsomolec** [Teplitsa/tst-yandex-feed#20]
В теме оформления моего сайта тизер поста (то, что до тега more) используется в качестве подзаголовка. В результате в yandex:full-text попадает подзаголовок, который там не нужен.
Можно ли отфильтровать тизер и не выдавать его в yandex:full-text? Сам так и не смог разобраться, как это можно сделать.

**Comment by DenisCherniatev** [comment]
Элемент yandex:full-text включает в себя весь контент записи, включая тизер. И на данный момент отдельной опции исключения оттуда тизера нет. Мы рассмотрим добавление такой опции в следующей версии плагина.

**Comment by DenisCherniatev** [comment]
Выпущена новая версия плагина, в которой добавлена опция удаления тизера из содержимого тэга yandex:full-text. Будем благодарны за тестирование.
