### ISSUE TITLE
Количество записей в ленте

### ISSUE THREAD

**Issue by kvitenUA** [Teplitsa/tst-yandex-feed#21]
Иногда нужно лимитировать количество записей для RSS ленты. Поэтому в  функции custom_request($query) файла tst-yandex-feed-core.php приходится ручками править значение атрибута массива $query->query_vars['posts_per_page'] = -1;

Сделайте переменной и закрепите в опциях) Многим пригодится.

**Comment by DenisCherniatev** [comment]
Спасибо за предложение. Мы рассмотрим добавление этой опции в следующую версию плагина.

**Comment by DenisCherniatev** [comment]
Выпущена новая версия плагина, в которой добавлено опциональное ограничение длины фида. Будем благодарны за тестирование.
