### ISSUE TITLE
Не сохраняется настройка в базе

### ISSUE THREAD

**Issue by smspivak** [Teplitsa/tst-yandex-feed#22]
Не работает галка "Исключить запись из трансляции Яндекс.Новости"
"Типы записей для трансляции" в настройках нужно указывать явно, тогда все ОК.

**Comment by DenisCherniatev** [comment]
Актуальная версия плагина - 1.8.5. У вас установлена последняя версия плагина?

**Comment by smspivak** [comment]
Да, последняя. Проблема решается, если явно указать типы записей в настройках плагина. Посмотрел код, там проверка стоит.
