### ISSUE TITLE
Исключение из RSS тегов Visual Composer

### ISSUE THREAD

**Issue by Kopaev** [Teplitsa/tst-yandex-feed#23]
Каким образом можно можно исключить из RSS тегов Visual Composer
Ато в ленте яндекс новостей не красиво смотрится https://yadi.sk/i/cezrhzCqq9sUf

**Comment by DenisCherniatev** [comment]
Спасибо за сообщение о проблеме. Добавим фильтрацию этих тэгов в следующей версии плагина.

**Comment by DenisCherniatev** [comment]
Выпущена новая версия плагина, в которой добавлена опция удаления неотработавших шорткодов, в том числе и тэгов Visual Composer.
