### ISSUE TITLE
Не сохраняется "Исключить, не смотря на глобальные настройки"

### ISSUE THREAD

**Issue by jeebus3000** [Teplitsa/tst-yandex-feed#25]
Здравствуйте!
Установил самую последнюю версию вашего плагина.
Не работает исключение конкретных записей из фида. Я проверял на уже существующих записях. Установил галочку "Исключить, не смотря на глобальные настройки", нажал кнопку виджета публикации "обновить" и галочка сбрасывается. Запись не пропадает из фида.

**Comment by jeebus3000** [comment]
Извините! На локальном работает. Проблема в другом.

**Comment by DenisCherniatev** [comment]
Здравствуйте! А в чем именно была проблема?

**Comment by jeebus3000** [comment]
Здравствуйте!
Не знаю. Думал, из-за многоуровневого кеширования, отключили на админке, не помогло.
Пока используем костыль в виде исключения категорий. В ближайшее время обновлю сам вордпресс, посмотрим.

**Comment by DenisCherniatev** [comment]
Если в настройках плагина поле "Типы записей для трансляции" пустое, попробуйте указать там post.

**Comment by jeebus3000** [comment]
Сработало! Спасибо!
