### ISSUE TITLE
Турбо-страницы

### ISSUE THREAD

**Issue by uaalex** [Teplitsa/tst-yandex-feed#30]
Поставил плагин.
Все ок!
Спасибо разработчикам!
Яндекс принял фид.
Но для турбо-страниц просит:

"Добавьте также, пожалуйста, элемент <header> с заголовком сообщения в тег <turbo:content>. Пример:
https://yandex.ru/support/news/feed.html#rss-elements__turbo-content-details"

Подскажите, как подправить код?

**Comment by DenisCherniatev** [comment]
В последней версии плагина добавлена возможность активировать поддержку турбо-страниц. Для этого в настройках плагина нужно включить опцию "Включить поддержку турбо-страниц".

Чтобы у записи в ленте появилась обложка для турбо-контента, нужно задать миниатюру этой записи. Тогда в элементе ленты, внутри тэга <turbo:content>, должен появиться <header> с вложенным элементом <h1>(заголовок обложки) и <figure>(картинка).

**Comment by uaalex** [comment]
Спасибо!
