### ISSUE TITLE
Требования Яндекса изменились

### ISSUE THREAD

**Issue by egor-belikov** [Teplitsa/tst-yandex-feed#4]
Надо бы проверить, что именно изменилось, и выполняются ли теперь требования. Может, у вас есть предыдущие требования? https://partner.news.yandex.ru/tech.pdf

**Comment by foralien** [comment]
Спасибо за информацию, на вскидку каких-то драмматических отличий от того, что было - не вижу. Во время последних изменений (когда изменился формат логотипа), мы получили уведомление от Яндекса. Но в любом случае проверим более предметно. 
Будем также признательны за информацию об ошибках, если у вас вдруг такие станут появляться.
