### ISSUE TITLE
Максимальный возраст записей ленты - игнорируется?

### ISSUE THREAD

**Issue by DuDlikSPB** [Teplitsa/tst-yandex-feed#44]
Добрый день

А какова логика плагина?

Я ставлю - Максимальный возраст записей ленты - 1 день
Мне в RSS выдается гора записей месяц +

Как связаны дни и Лимит количества записей в ленте?

**Comment by chebotar** [comment]
+1 не работает ограничение по записям, выводит очень много записей

**Comment by DenisCherniatev** [comment]
Если включена поддержка турбо, то по умолчанию размер ленты равен 300 записям. Параметр максимального возраста записи в этом случае игнорируется.
