### ISSUE TITLE
Пара предложений по улучшению

### ISSUE THREAD

**Issue by egor-belikov** [Teplitsa/tst-yandex-feed#5]
* Добавить возможность создания нескольких одинаковых лент (для Яндекса, Рамблера etc.)
* Убирать из полного текста шорткоды.

**Comment by foralien** [comment]
Спасибо за идеи - но насчет других лент пока не могу обещать - не анализировали пока насколько сильно расходятся их требования. Был опыт с Google но там несколько "совсем другой подход" - так что мы на него пока не возьмемся наверное.
Про шорткоды подход по умолчанию такой - что они "раскрываются" и потом убираются все HTML теги которые получились, а текствое содержание остается. Если вам нужно как-то иначе - то нужно отфильтровывать содержание поста с более высоким приоритетом, чем срабатывают наши фильтры.
