### ISSUE TITLE
ОШИБКА: Текущий шаблон не является корректным шаблоном ленты.

### ISSUE THREAD

**Issue by lubimow** [Teplitsa/tst-yandex-feed#7]
Здравствуйте. 
Установил ваш плагин и мне выдает ошибку по адресу фида:
ОШИБКА: Текущий шаблон не является корректным шаблоном ленты.

что делать ?

**Comment by foralien** [comment]
Укажите пожалуйста ссылку на фид - если это возможно.
Какой браузер вы используете? Возможно ваш браузер некорретно отображает фид, потому что строго говоря он "не является корректным шаблоном ленты" из-за кастомных тэгов Яндекса. Попробуйте открыть в Google Chrome - который показывает исходный код фида без какой-либо обработки. Однако если это не браузер, то в слепую сложно сказать в чем дело, возможно конфликт с темой или каким-либо из плагинов, возможно еще что-то... Включите Debug mode и логгинг в конфиге и скажите пожалуйста нет ли в логе сообщений об ошибках.

**Comment by lubimow** [comment]
я открывал ленту в Chrome 
вот фид
http://inforesist.org/feed/yandex/
Debug mode включил

**Comment by lubimow** [comment]
пришлось временно отключить ваш плагин - не могу чтобы ночь не работал
с утра его опять активирую потестим

**Comment by foralien** [comment]
думаю, проблема в URL... 
стандартный урл, по которому работает наш плагин http://inforesist.org/yandex/news/
Видимо вы изменили его на кастомный http://inforesist.org/feed/yandex/ - однако в этом случае происходит конфликт с корневым поведением ВП, которая с одной стороны "думает" что загружает обычный фид, а с другой там есть наша query_var по которой определяется необходимость подгрузки кастомного шаблона.
Короче, попробуйте убрать слово feed из URL

**Comment by lubimow** [comment]
я сменил адрес
http://inforesist.org/yandex/feed/ 
но теперь ничего не грузит в фид

**Comment by DenisCherniatev** [comment]
Вышла новая версия плагина. Попробуйте обновить его на вашем сайте. Возможно это решит вашу проблему.
Если нет, то возможная причина в следующем: в настройках плагина указан несуществующий типы записей для трансляции, или за последнюю неделю не было добавлено ни одной записи такого типа.
