### ISSUE TITLE
Как в фиде сменить изображение из записи на миниатюру?

### ISSUE THREAD

**Issue by Irridian** [Teplitsa/tst-yandex-feed#8]
Добрый день!

Собственно, вопрос в сабже. Возникала такая необходимость по той причине, что даже на странице  с новостью выводящееся изображение это не прикрепленный к записи файл, а миниатюра записи, которая выводится таким кодом:

<?php if ( has_post_thumbnail()): ?><?php the_post_thumbnail(array(360,360), array("class" => "alignleft post_thumbnail"));  ?><?php endif;?>

Собственно, как быть с заменой в теге enclosure в фиде, под обозначенные нужды? Есть ли решение?

**Comment by DenisCherniatev** [comment]
В следующей версии плагина мы добавим такую возможность. На данный момент решить проблему поможет редактирование кода плагина. Файл /tst-yandex-feed-master/inc/tst-yandex-feed-core.php, метод item_enclosure

**Comment by Irridian** [comment]
Увы, в силу ограниченности знаний самостоятельно подправить код не получается.

Можете подсказать, когда ориентировочно стоит знать обновления?

Заранее спасибо!

**Comment by Irridian** [comment]
Есть тут кто? :1234: )

**Comment by DenisCherniatev** [comment]
Обновление планируем выпустить на следующей неделе.

**Comment by DenisCherniatev** [comment]
Вышла новая версия плагина. В ней выдача миниатюр оптимизирована и добавлена поддержка миниатюр для видео с youtube. Попробуйте обновить плагин на сайте.
