### ISSUE TITLE
Пустой экран по ссылке RSS-канала

### ISSUE THREAD

**Issue by Boooober** [Teplitsa/tst-yandex-feed#9]
Здравствуйте! Использую ваш замечательный плагин на нескольких своих сайтах. Проблема возникла с сайтом, который находится на VPS GoDaddy. По ссылке site.net/yandex/news ничего нету - белый экран. Пробовал выключать все плагины и чистить кеш - не помогло. При этом другие (стандартные каналы типа site.net/feed) работают. 
Какие решения данной проблемы вам видны?
Заранее спасибо!

**Comment by DenisCherniatev** [comment]
Решить проблему можно попытаться следующими способоами:
1. Пересохранить настройки в разделе "Настройки" -> "Постоянные ссылки" (Permalinks)
2. Если не помогло, то нужно проверить, если ли записи нужного типа, созданные за последние 7 дней. Если таких нет, то фид может не отображаться.
3. Если п.1 и п.2. не помогли, нужно переводить WP в DEBUG_MODE, разрешать все сообщения об ошибках PHP и искать ошибку в коде сайта.

**Comment by DenisCherniatev** [comment]
Вышла новая версия плагина. Попробуйте обновить плагин на сайте, возможно это решит проблему.
